name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Linter (ESLint)
      run: npm run lint

    - name: Formatter (Prettier)
      run: npm run prettier

    - name: Test (Jest)
      run: npm run test -- --env=jsdom

    - name: Build
      run: npm run build
